name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aist-front-auto:latest
      
    - name: Run image
      run: docker run -dp 127.0.0.1:3000:3000 aist-front-auto:latest
